name: Build

on:
  workflow_call:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [14.x, 16.x]
        os: ['ubuntu-latest', 'windows-latest', 'macOS-latest']

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Instal dependencies
        run: npm install
      - name: Create a build
        run: npm run build --if-present
      #- name: Save build folders
      #  uses: actions/upload-artifact@v2
      #  with:
      #    name: install-and-build
      #    path: |
      #      build
