name: CI/CD

on:
  workflow_dispatch:

  pull_request:
    branches: [master]

jobs:
  CI:
    uses: Zexal0807/runtheons-session-manager/.github/workflows/CI.yml@master

  CD:
    needs: CI
    uses: Zexal0807/runtheons-session-manager/.github/workflows/deploy.yml@master
