name: CI/CD

on:
  workflow_dispatch:

  pull_request:
    branches: [production]

jobs:
  test:
    name: Test
    uses: Zexal0807/runtheons-CI-CD/.github/workflows/test.yml@main

  build:
    name: Build
    needs: test
    uses: Zexal0807/runtheons-CI-CD/.github/workflows/build.yml@main

  # deploy:
  #   uses: Zexal0807/runtheons-CI-CD/.github/workflows/deploy.yml@main
