name: CI/CD

on:
  workflow_dispatch:

  pull_request:
    branches: [master]

jobs:
  test:
    uses: Zexal0807/runtheons-CI-CD/workflows/test.yml@master

  build:
    uses: Zexal0807/runtheons-CI-CD/workflows/build.yml@master

  deploy:
    uses: Zexal0807/runtheons-CI-CD/workflows/deploy.yml@master
